apiVersion: v1
kind: Service
metadata:
  name: grpc-helloworld
  labels:
    app: grpc-helloworld
spec:
  type: NodePort
  ports:
  - name: grpc-helloworld
    port: 50051
    targetPort: 50051
    nodePort: 30300
  selector:
    app: grpc-helloworld
