apiVersion: v1
kind: Service
metadata:
  name: aa
  labels:
    app: federated-cluster
spec:
  type: NodePort
  selector:
    app: federated-cluster
    module: federation-apiserver
  ports:
    - name: https
      protocol: TCP
      nodePort: 30011
      port: 8899
