apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tensorflow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: tensorflow
        image: tensorflow/tensorflow
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8888
        - containerPort: 6006
