apiVersion: v1
kind: Service
metadata:
  name: tensorflow
  labels:
    app: redis
    role: master
    tier: backend
spec:
  type: NodePort
  ports:
  - name: tensorflow
    port: 8888
    nodePort: 30001
  - name: tensorboard
    port: 6006
    nodePort: 30002
  selector:
    app: redis
    role: master
    tier: backend
