apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: seagull
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: seagull
        image: tobegit3hub/seagull
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 10086
